// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/verification/v1/message.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumVerification int32

const (
	EnumVerification_Undefined EnumVerification = 0
	EnumVerification_Email     EnumVerification = 1
	EnumVerification_Mobile    EnumVerification = 2
)

// Enum value maps for EnumVerification.
var (
	EnumVerification_name = map[int32]string{
		0: "Undefined",
		1: "Email",
		2: "Mobile",
	}
	EnumVerification_value = map[string]int32{
		"Undefined": 0,
		"Email":     1,
		"Mobile":    2,
	}
)

func (x EnumVerification) Enum() *EnumVerification {
	p := new(EnumVerification)
	*p = x
	return p
}

func (x EnumVerification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumVerification) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_verification_v1_message_proto_enumTypes[0].Descriptor()
}

func (EnumVerification) Type() protoreflect.EnumType {
	return &file_pkg_proto_verification_v1_message_proto_enumTypes[0]
}

func (x EnumVerification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumVerification.Descriptor instead.
func (EnumVerification) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_verification_v1_message_proto_rawDescGZIP(), []int{0}
}

type ListVerificationMethodsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVerificationMethodsReq) Reset() {
	*x = ListVerificationMethodsReq{}
	mi := &file_pkg_proto_verification_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVerificationMethodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerificationMethodsReq) ProtoMessage() {}

func (x *ListVerificationMethodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_verification_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerificationMethodsReq.ProtoReflect.Descriptor instead.
func (*ListVerificationMethodsReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_verification_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *ListVerificationMethodsReq) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type VerificationMethod struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	VerificationMethod EnumVerification       `protobuf:"varint,1,opt,name=verification_method,json=verificationMethod,proto3,enum=nortoo.usms.verification.v1.EnumVerification" json:"verification_method,omitempty"`
	Target             string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VerificationMethod) Reset() {
	*x = VerificationMethod{}
	mi := &file_pkg_proto_verification_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationMethod) ProtoMessage() {}

func (x *VerificationMethod) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_verification_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationMethod.ProtoReflect.Descriptor instead.
func (*VerificationMethod) Descriptor() ([]byte, []int) {
	return file_pkg_proto_verification_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *VerificationMethod) GetVerificationMethod() EnumVerification {
	if x != nil {
		return x.VerificationMethod
	}
	return EnumVerification_Undefined
}

func (x *VerificationMethod) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type ListVerificationMethodsResp struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	AvailableVerificationMethods []*VerificationMethod  `protobuf:"bytes,1,rep,name=available_verification_methods,json=availableVerificationMethods,proto3" json:"available_verification_methods,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ListVerificationMethodsResp) Reset() {
	*x = ListVerificationMethodsResp{}
	mi := &file_pkg_proto_verification_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVerificationMethodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerificationMethodsResp) ProtoMessage() {}

func (x *ListVerificationMethodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_verification_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerificationMethodsResp.ProtoReflect.Descriptor instead.
func (*ListVerificationMethodsResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_verification_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *ListVerificationMethodsResp) GetAvailableVerificationMethods() []*VerificationMethod {
	if x != nil {
		return x.AvailableVerificationMethods
	}
	return nil
}

type GetVerificationTargetReq struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	VerificationMethod EnumVerification       `protobuf:"varint,1,opt,name=verification_method,json=verificationMethod,proto3,enum=nortoo.usms.verification.v1.EnumVerification" json:"verification_method,omitempty"`
	Identifier         string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetVerificationTargetReq) Reset() {
	*x = GetVerificationTargetReq{}
	mi := &file_pkg_proto_verification_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerificationTargetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerificationTargetReq) ProtoMessage() {}

func (x *GetVerificationTargetReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_verification_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerificationTargetReq.ProtoReflect.Descriptor instead.
func (*GetVerificationTargetReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_verification_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *GetVerificationTargetReq) GetVerificationMethod() EnumVerification {
	if x != nil {
		return x.VerificationMethod
	}
	return EnumVerification_Undefined
}

func (x *GetVerificationTargetReq) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type GetVerificationTargetResp struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	VerificationMethod EnumVerification       `protobuf:"varint,1,opt,name=verification_method,json=verificationMethod,proto3,enum=nortoo.usms.verification.v1.EnumVerification" json:"verification_method,omitempty"`
	Target             string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetVerificationTargetResp) Reset() {
	*x = GetVerificationTargetResp{}
	mi := &file_pkg_proto_verification_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerificationTargetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerificationTargetResp) ProtoMessage() {}

func (x *GetVerificationTargetResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_verification_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerificationTargetResp.ProtoReflect.Descriptor instead.
func (*GetVerificationTargetResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_verification_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *GetVerificationTargetResp) GetVerificationMethod() EnumVerification {
	if x != nil {
		return x.VerificationMethod
	}
	return EnumVerification_Undefined
}

func (x *GetVerificationTargetResp) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

var File_pkg_proto_verification_v1_message_proto protoreflect.FileDescriptor

const file_pkg_proto_verification_v1_message_proto_rawDesc = "" +
	"\n" +
	"'pkg/proto/verification/v1/message.proto\x12\x1bnortoo.usms.verification.v1\"<\n" +
	"\x1aListVerificationMethodsReq\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\"\x8c\x01\n" +
	"\x12VerificationMethod\x12^\n" +
	"\x13verification_method\x18\x01 \x01(\x0e2-.nortoo.usms.verification.v1.EnumVerificationR\x12verificationMethod\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"\x94\x01\n" +
	"\x1bListVerificationMethodsResp\x12u\n" +
	"\x1eavailable_verification_methods\x18\x01 \x03(\v2/.nortoo.usms.verification.v1.VerificationMethodR\x1cavailableVerificationMethods\"\x9a\x01\n" +
	"\x18GetVerificationTargetReq\x12^\n" +
	"\x13verification_method\x18\x01 \x01(\x0e2-.nortoo.usms.verification.v1.EnumVerificationR\x12verificationMethod\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\"\x93\x01\n" +
	"\x19GetVerificationTargetResp\x12^\n" +
	"\x13verification_method\x18\x01 \x01(\x0e2-.nortoo.usms.verification.v1.EnumVerificationR\x12verificationMethod\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target*8\n" +
	"\x10EnumVerification\x12\r\n" +
	"\tUndefined\x10\x00\x12\t\n" +
	"\x05Email\x10\x01\x12\n" +
	"\n" +
	"\x06Mobile\x10\x02B5Z3github.com/nortoo/usms/pkg/proto/verification/v1;v1b\x06proto3"

var (
	file_pkg_proto_verification_v1_message_proto_rawDescOnce sync.Once
	file_pkg_proto_verification_v1_message_proto_rawDescData []byte
)

func file_pkg_proto_verification_v1_message_proto_rawDescGZIP() []byte {
	file_pkg_proto_verification_v1_message_proto_rawDescOnce.Do(func() {
		file_pkg_proto_verification_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_verification_v1_message_proto_rawDesc), len(file_pkg_proto_verification_v1_message_proto_rawDesc)))
	})
	return file_pkg_proto_verification_v1_message_proto_rawDescData
}

var file_pkg_proto_verification_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_verification_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_verification_v1_message_proto_goTypes = []any{
	(EnumVerification)(0),               // 0: nortoo.usms.verification.v1.EnumVerification
	(*ListVerificationMethodsReq)(nil),  // 1: nortoo.usms.verification.v1.ListVerificationMethodsReq
	(*VerificationMethod)(nil),          // 2: nortoo.usms.verification.v1.VerificationMethod
	(*ListVerificationMethodsResp)(nil), // 3: nortoo.usms.verification.v1.ListVerificationMethodsResp
	(*GetVerificationTargetReq)(nil),    // 4: nortoo.usms.verification.v1.GetVerificationTargetReq
	(*GetVerificationTargetResp)(nil),   // 5: nortoo.usms.verification.v1.GetVerificationTargetResp
}
var file_pkg_proto_verification_v1_message_proto_depIdxs = []int32{
	0, // 0: nortoo.usms.verification.v1.VerificationMethod.verification_method:type_name -> nortoo.usms.verification.v1.EnumVerification
	2, // 1: nortoo.usms.verification.v1.ListVerificationMethodsResp.available_verification_methods:type_name -> nortoo.usms.verification.v1.VerificationMethod
	0, // 2: nortoo.usms.verification.v1.GetVerificationTargetReq.verification_method:type_name -> nortoo.usms.verification.v1.EnumVerification
	0, // 3: nortoo.usms.verification.v1.GetVerificationTargetResp.verification_method:type_name -> nortoo.usms.verification.v1.EnumVerification
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_verification_v1_message_proto_init() }
func file_pkg_proto_verification_v1_message_proto_init() {
	if File_pkg_proto_verification_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_verification_v1_message_proto_rawDesc), len(file_pkg_proto_verification_v1_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_verification_v1_message_proto_goTypes,
		DependencyIndexes: file_pkg_proto_verification_v1_message_proto_depIdxs,
		EnumInfos:         file_pkg_proto_verification_v1_message_proto_enumTypes,
		MessageInfos:      file_pkg_proto_verification_v1_message_proto_msgTypes,
	}.Build()
	File_pkg_proto_verification_v1_message_proto = out.File
	file_pkg_proto_verification_v1_message_proto_goTypes = nil
	file_pkg_proto_verification_v1_message_proto_depIdxs = nil
}
