// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/verification/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pkg_proto_verification_v1_service_proto protoreflect.FileDescriptor

const file_pkg_proto_verification_v1_service_proto_rawDesc = "" +
	"\n" +
	"'pkg/proto/verification/v1/service.proto\x12\x1bnortoo.usms.verification.v1\x1a'pkg/proto/verification/v1/message.proto2\xa1\x02\n" +
	"\aService\x12\x8c\x01\n" +
	"\x17ListVerificationMethods\x127.nortoo.usms.verification.v1.ListVerificationMethodsReq\x1a8.nortoo.usms.verification.v1.ListVerificationMethodsResp\x12\x86\x01\n" +
	"\x15GetVerificationTarget\x125.nortoo.usms.verification.v1.GetVerificationTargetReq\x1a6.nortoo.usms.verification.v1.GetVerificationTargetRespB5Z3github.com/nortoo/usms/pkg/proto/verification/v1;v1b\x06proto3"

var file_pkg_proto_verification_v1_service_proto_goTypes = []any{
	(*ListVerificationMethodsReq)(nil),  // 0: nortoo.usms.verification.v1.ListVerificationMethodsReq
	(*GetVerificationTargetReq)(nil),    // 1: nortoo.usms.verification.v1.GetVerificationTargetReq
	(*ListVerificationMethodsResp)(nil), // 2: nortoo.usms.verification.v1.ListVerificationMethodsResp
	(*GetVerificationTargetResp)(nil),   // 3: nortoo.usms.verification.v1.GetVerificationTargetResp
}
var file_pkg_proto_verification_v1_service_proto_depIdxs = []int32{
	0, // 0: nortoo.usms.verification.v1.Service.ListVerificationMethods:input_type -> nortoo.usms.verification.v1.ListVerificationMethodsReq
	1, // 1: nortoo.usms.verification.v1.Service.GetVerificationTarget:input_type -> nortoo.usms.verification.v1.GetVerificationTargetReq
	2, // 2: nortoo.usms.verification.v1.Service.ListVerificationMethods:output_type -> nortoo.usms.verification.v1.ListVerificationMethodsResp
	3, // 3: nortoo.usms.verification.v1.Service.GetVerificationTarget:output_type -> nortoo.usms.verification.v1.GetVerificationTargetResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_verification_v1_service_proto_init() }
func file_pkg_proto_verification_v1_service_proto_init() {
	if File_pkg_proto_verification_v1_service_proto != nil {
		return
	}
	file_pkg_proto_verification_v1_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_verification_v1_service_proto_rawDesc), len(file_pkg_proto_verification_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_verification_v1_service_proto_goTypes,
		DependencyIndexes: file_pkg_proto_verification_v1_service_proto_depIdxs,
	}.Build()
	File_pkg_proto_verification_v1_service_proto = out.File
	file_pkg_proto_verification_v1_service_proto_goTypes = nil
	file_pkg_proto_verification_v1_service_proto_depIdxs = nil
}
