app:
  snowflake_id: 64
  certs:
    ca_file: conf/certs/ca/ca.pem
    key_file: conf/certs/server/server.key
    cert_file: conf/certs/server/server.crt
  settings:
    jwt:
      token_expire_time: 3600  # in seconds
      token_refresh_time: 2592000  # in seconds

    validation:
      username_pattern:
        min_length: 5
        max_length: 20
      password_pattern:
        min_length: 8
        require_upper_case: true
        require_lower_case: true
        require_digit: true
        require_special_chars: true

    default_value:
      user_state: 1
      
store:
  mysql:
    default:
      host: 127.0.0.1
      port: 3306
      user: root
      password: placeholder
      db: dbname

  redis:
    host: 127.0.0.1
    port: 6379
    password: placeholder