// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/application/v1/message.proto

package v1

import (
	types "github.com/nortoo/usms/pkg/proto/common/v1/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Application defines the data model of an application.
type Application struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the application.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Appid of the application.
	Appid string `protobuf:"bytes,3,opt,name=appid,proto3" json:"appid,omitempty"`
	// Secretkey of the application.
	SecretKey     string           `protobuf:"bytes,4,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Comment       string           `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	State         int32            `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	Time          *types.TimeModel `protobuf:"bytes,7,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_pkg_proto_application_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_application_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_pkg_proto_application_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Application) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *Application) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *Application) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Application) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Application) GetTime() *types.TimeModel {
	if x != nil {
		return x.Time
	}
	return nil
}

// CreateReq is the request model of creating an new Application.
type CreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	mi := &file_pkg_proto_application_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_application_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_application_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// DeleteReq is the parameter to delete an application.
type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_pkg_proto_application_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_application_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_application_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// UpdateReq is the parameter to update an application.
type UpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	State         int32                  `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReq) Reset() {
	*x = UpdateReq{}
	mi := &file_pkg_proto_application_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReq) ProtoMessage() {}

func (x *UpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_application_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReq.ProtoReflect.Descriptor instead.
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_application_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *UpdateReq) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

// GetReq is the parameters to get an application.
type GetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Appid         string                 `protobuf:"bytes,3,opt,name=appid,proto3" json:"appid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_pkg_proto_application_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_application_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_application_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *GetReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetReq) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

// ListReq is the parameter to list applications.
type ListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *types.Pagination      `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReq) Reset() {
	*x = ListReq{}
	mi := &file_pkg_proto_application_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReq) ProtoMessage() {}

func (x *ListReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_application_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReq.ProtoReflect.Descriptor instead.
func (*ListReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_application_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *ListReq) GetPagination() *types.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *types.PaginationResp  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Items         []*Application         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResp) Reset() {
	*x = ListResp{}
	mi := &file_pkg_proto_application_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResp) ProtoMessage() {}

func (x *ListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_application_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResp.ProtoReflect.Descriptor instead.
func (*ListResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_application_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *ListResp) GetPagination() *types.PaginationResp {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListResp) GetItems() []*Application {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_pkg_proto_application_v1_message_proto protoreflect.FileDescriptor

const file_pkg_proto_application_v1_message_proto_rawDesc = "" +
	"\n" +
	"&pkg/proto/application/v1/message.proto\x12\x1anortoo.usms.application.v1\x1a&pkg/proto/common/v1/types/shared.proto\"\xd2\x01\n" +
	"\vApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05appid\x18\x03 \x01(\tR\x05appid\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x04 \x01(\tR\tsecretKey\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x14\n" +
	"\x05state\x18\x06 \x01(\x05R\x05state\x12:\n" +
	"\x04time\x18\a \x01(\v2&.nortoo.usms.common.v1.types.TimeModelR\x04time\"9\n" +
	"\tCreateReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\"\x1b\n" +
	"\tDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"K\n" +
	"\tUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x14\n" +
	"\x05state\x18\x03 \x01(\x05R\x05state\"B\n" +
	"\x06GetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05appid\x18\x03 \x01(\tR\x05appid\"R\n" +
	"\aListReq\x12G\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2'.nortoo.usms.common.v1.types.PaginationR\n" +
	"pagination\"\x96\x01\n" +
	"\bListResp\x12K\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2+.nortoo.usms.common.v1.types.PaginationRespR\n" +
	"pagination\x12=\n" +
	"\x05items\x18\x02 \x03(\v2'.nortoo.usms.application.v1.ApplicationR\x05itemsB4Z2github.com/nortoo/usms/pkg/proto/application/v1;v1b\x06proto3"

var (
	file_pkg_proto_application_v1_message_proto_rawDescOnce sync.Once
	file_pkg_proto_application_v1_message_proto_rawDescData []byte
)

func file_pkg_proto_application_v1_message_proto_rawDescGZIP() []byte {
	file_pkg_proto_application_v1_message_proto_rawDescOnce.Do(func() {
		file_pkg_proto_application_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_application_v1_message_proto_rawDesc), len(file_pkg_proto_application_v1_message_proto_rawDesc)))
	})
	return file_pkg_proto_application_v1_message_proto_rawDescData
}

var file_pkg_proto_application_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_application_v1_message_proto_goTypes = []any{
	(*Application)(nil),          // 0: nortoo.usms.application.v1.Application
	(*CreateReq)(nil),            // 1: nortoo.usms.application.v1.CreateReq
	(*DeleteReq)(nil),            // 2: nortoo.usms.application.v1.DeleteReq
	(*UpdateReq)(nil),            // 3: nortoo.usms.application.v1.UpdateReq
	(*GetReq)(nil),               // 4: nortoo.usms.application.v1.GetReq
	(*ListReq)(nil),              // 5: nortoo.usms.application.v1.ListReq
	(*ListResp)(nil),             // 6: nortoo.usms.application.v1.ListResp
	(*types.TimeModel)(nil),      // 7: nortoo.usms.common.v1.types.TimeModel
	(*types.Pagination)(nil),     // 8: nortoo.usms.common.v1.types.Pagination
	(*types.PaginationResp)(nil), // 9: nortoo.usms.common.v1.types.PaginationResp
}
var file_pkg_proto_application_v1_message_proto_depIdxs = []int32{
	7, // 0: nortoo.usms.application.v1.Application.time:type_name -> nortoo.usms.common.v1.types.TimeModel
	8, // 1: nortoo.usms.application.v1.ListReq.pagination:type_name -> nortoo.usms.common.v1.types.Pagination
	9, // 2: nortoo.usms.application.v1.ListResp.pagination:type_name -> nortoo.usms.common.v1.types.PaginationResp
	0, // 3: nortoo.usms.application.v1.ListResp.items:type_name -> nortoo.usms.application.v1.Application
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_application_v1_message_proto_init() }
func file_pkg_proto_application_v1_message_proto_init() {
	if File_pkg_proto_application_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_application_v1_message_proto_rawDesc), len(file_pkg_proto_application_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_application_v1_message_proto_goTypes,
		DependencyIndexes: file_pkg_proto_application_v1_message_proto_depIdxs,
		MessageInfos:      file_pkg_proto_application_v1_message_proto_msgTypes,
	}.Build()
	File_pkg_proto_application_v1_message_proto = out.File
	file_pkg_proto_application_v1_message_proto_goTypes = nil
	file_pkg_proto_application_v1_message_proto_depIdxs = nil
}
