// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pkg/proto/user/v1/message.proto

package v1

import (
	types "github.com/nortoo/usms/pkg/proto/common/v1/types"
	v1 "github.com/nortoo/usms/pkg/proto/role/v1"
	v11 "github.com/nortoo/usms/pkg/proto/usergroup/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Roles         []*v1.Role             `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	Groups        []*v11.Group           `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty"`
	State         int32                  `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`
	Time          *types.TimeModel       `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *User) GetRoles() []*v1.Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetGroups() []*v11.Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *User) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *User) GetTime() *types.TimeModel {
	if x != nil {
		return x.Time
	}
	return nil
}

type CreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Roles         []int64                `protobuf:"varint,5,rep,packed,name=roles,proto3" json:"roles,omitempty"`
	Groups        []int64                `protobuf:"varint,6,rep,packed,name=groups,proto3" json:"groups,omitempty"`
	State         int32                  `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CreateReq) GetRoles() []int64 {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *CreateReq) GetGroups() []int64 {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *CreateReq) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Roles         []int64                `protobuf:"varint,5,rep,packed,name=roles,proto3" json:"roles,omitempty"`
	Groups        []int64                `protobuf:"varint,6,rep,packed,name=groups,proto3" json:"groups,omitempty"`
	State         int32                  `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReq) Reset() {
	*x = UpdateReq{}
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReq) ProtoMessage() {}

func (x *UpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReq.ProtoReflect.Descriptor instead.
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UpdateReq) GetRoles() []int64 {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UpdateReq) GetGroups() []int64 {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *UpdateReq) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type GetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *GetReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	State         []int32                `protobuf:"varint,4,rep,packed,name=state,proto3" json:"state,omitempty"`
	GroupId       uint64                 `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	RoleId        uint64                 `protobuf:"varint,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Pagination    *types.Pagination      `protobuf:"bytes,7,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReq) Reset() {
	*x = ListReq{}
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReq) ProtoMessage() {}

func (x *ListReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReq.ProtoReflect.Descriptor instead.
func (*ListReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *ListReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ListReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ListReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ListReq) GetState() []int32 {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ListReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ListReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *ListReq) GetPagination() *types.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *types.PaginationResp  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Items         []*User                `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResp) Reset() {
	*x = ListResp{}
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResp) ProtoMessage() {}

func (x *ListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResp.ProtoReflect.Descriptor instead.
func (*ListResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *ListResp) GetPagination() *types.PaginationResp {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListResp) GetItems() []*User {
	if x != nil {
		return x.Items
	}
	return nil
}

type SignupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Roles         []uint64               `protobuf:"varint,5,rep,packed,name=roles,proto3" json:"roles,omitempty"`
	Groups        []uint64               `protobuf:"varint,6,rep,packed,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupReq) Reset() {
	*x = SignupReq{}
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupReq) ProtoMessage() {}

func (x *SignupReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupReq.ProtoReflect.Descriptor instead.
func (*SignupReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_v1_message_proto_rawDescGZIP(), []int{7}
}

func (x *SignupReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignupReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignupReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignupReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *SignupReq) GetRoles() []uint64 {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *SignupReq) GetGroups() []uint64 {
	if x != nil {
		return x.Groups
	}
	return nil
}

type LoginReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// identifier can be either email or mobile
	Identifier    string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_v1_message_proto_rawDescGZIP(), []int{8}
}

func (x *LoginReq) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     uint32                 `protobuf:"varint,5,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_v1_message_proto_rawDescGZIP(), []int{9}
}

func (x *LoginResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResp) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *LoginResp) GetExpiresIn() uint32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type AuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Tenant        string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_v1_message_proto_rawDescGZIP(), []int{10}
}

func (x *AuthReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthReq) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *AuthReq) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuthReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type AuthResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Authorized    bool                   `protobuf:"varint,2,opt,name=authorized,proto3" json:"authorized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResp) Reset() {
	*x = AuthResp{}
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResp) ProtoMessage() {}

func (x *AuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_v1_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResp.ProtoReflect.Descriptor instead.
func (*AuthResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_v1_message_proto_rawDescGZIP(), []int{11}
}

func (x *AuthResp) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AuthResp) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

var File_pkg_proto_user_v1_message_proto protoreflect.FileDescriptor

const file_pkg_proto_user_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/user/v1/message.proto\x12\x13nortoo.usms.user.v1\x1a&pkg/proto/common/v1/types/shared.proto\x1a\x1fpkg/proto/role/v1/message.proto\x1a$pkg/proto/usergroup/v1/message.proto\"\x9c\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12/\n" +
	"\x05roles\x18\x05 \x03(\v2\x19.nortoo.usms.role.v1.RoleR\x05roles\x127\n" +
	"\x06groups\x18\x06 \x03(\v2\x1f.nortoo.usms.usergroup.v1.GroupR\x06groups\x12\x14\n" +
	"\x05state\x18\a \x01(\x05R\x05state\x12:\n" +
	"\x04time\x18\b \x01(\v2&.nortoo.usms.common.v1.types.TimeModelR\x04time\"\xb5\x01\n" +
	"\tCreateReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\x03R\x05roles\x12\x16\n" +
	"\x06groups\x18\x06 \x03(\x03R\x06groups\x12\x14\n" +
	"\x05state\x18\a \x01(\x05R\x05state\"\x1b\n" +
	"\tDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xa9\x01\n" +
	"\tUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\x03R\x05roles\x12\x16\n" +
	"\x06groups\x18\x06 \x03(\x03R\x06groups\x12\x14\n" +
	"\x05state\x18\a \x01(\x05R\x05state\"\x18\n" +
	"\x06GetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xe6\x01\n" +
	"\aListReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05state\x18\x04 \x03(\x05R\x05state\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\x04R\agroupId\x12\x17\n" +
	"\arole_id\x18\x06 \x01(\x04R\x06roleId\x12G\n" +
	"\n" +
	"pagination\x18\a \x01(\v2'.nortoo.usms.common.v1.types.PaginationR\n" +
	"pagination\"\x88\x01\n" +
	"\bListResp\x12K\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2+.nortoo.usms.common.v1.types.PaginationRespR\n" +
	"pagination\x12/\n" +
	"\x05items\x18\x02 \x03(\v2\x19.nortoo.usms.user.v1.UserR\x05items\"\x9f\x01\n" +
	"\tSignupReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\x04R\x05roles\x12\x16\n" +
	"\x06groups\x18\x06 \x03(\x04R\x06groups\"F\n" +
	"\bLoginReq\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xb3\x01\n" +
	"\tLoginResp\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.nortoo.usms.user.v1.UserR\x04user\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x05 \x01(\rR\texpiresIn\"k\n" +
	"\aAuthReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"<\n" +
	"\bAuthResp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x1e\n" +
	"\n" +
	"authorized\x18\x02 \x01(\bR\n" +
	"authorizedB-Z+github.com/nortoo/usms/pkg/proto/user/v1;v1b\x06proto3"

var (
	file_pkg_proto_user_v1_message_proto_rawDescOnce sync.Once
	file_pkg_proto_user_v1_message_proto_rawDescData []byte
)

func file_pkg_proto_user_v1_message_proto_rawDescGZIP() []byte {
	file_pkg_proto_user_v1_message_proto_rawDescOnce.Do(func() {
		file_pkg_proto_user_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_user_v1_message_proto_rawDesc), len(file_pkg_proto_user_v1_message_proto_rawDesc)))
	})
	return file_pkg_proto_user_v1_message_proto_rawDescData
}

var file_pkg_proto_user_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_proto_user_v1_message_proto_goTypes = []any{
	(*User)(nil),                 // 0: nortoo.usms.user.v1.User
	(*CreateReq)(nil),            // 1: nortoo.usms.user.v1.CreateReq
	(*DeleteReq)(nil),            // 2: nortoo.usms.user.v1.DeleteReq
	(*UpdateReq)(nil),            // 3: nortoo.usms.user.v1.UpdateReq
	(*GetReq)(nil),               // 4: nortoo.usms.user.v1.GetReq
	(*ListReq)(nil),              // 5: nortoo.usms.user.v1.ListReq
	(*ListResp)(nil),             // 6: nortoo.usms.user.v1.ListResp
	(*SignupReq)(nil),            // 7: nortoo.usms.user.v1.SignupReq
	(*LoginReq)(nil),             // 8: nortoo.usms.user.v1.LoginReq
	(*LoginResp)(nil),            // 9: nortoo.usms.user.v1.LoginResp
	(*AuthReq)(nil),              // 10: nortoo.usms.user.v1.AuthReq
	(*AuthResp)(nil),             // 11: nortoo.usms.user.v1.AuthResp
	(*v1.Role)(nil),              // 12: nortoo.usms.role.v1.Role
	(*v11.Group)(nil),            // 13: nortoo.usms.usergroup.v1.Group
	(*types.TimeModel)(nil),      // 14: nortoo.usms.common.v1.types.TimeModel
	(*types.Pagination)(nil),     // 15: nortoo.usms.common.v1.types.Pagination
	(*types.PaginationResp)(nil), // 16: nortoo.usms.common.v1.types.PaginationResp
}
var file_pkg_proto_user_v1_message_proto_depIdxs = []int32{
	12, // 0: nortoo.usms.user.v1.User.roles:type_name -> nortoo.usms.role.v1.Role
	13, // 1: nortoo.usms.user.v1.User.groups:type_name -> nortoo.usms.usergroup.v1.Group
	14, // 2: nortoo.usms.user.v1.User.time:type_name -> nortoo.usms.common.v1.types.TimeModel
	15, // 3: nortoo.usms.user.v1.ListReq.pagination:type_name -> nortoo.usms.common.v1.types.Pagination
	16, // 4: nortoo.usms.user.v1.ListResp.pagination:type_name -> nortoo.usms.common.v1.types.PaginationResp
	0,  // 5: nortoo.usms.user.v1.ListResp.items:type_name -> nortoo.usms.user.v1.User
	0,  // 6: nortoo.usms.user.v1.LoginResp.user:type_name -> nortoo.usms.user.v1.User
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_proto_user_v1_message_proto_init() }
func file_pkg_proto_user_v1_message_proto_init() {
	if File_pkg_proto_user_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_user_v1_message_proto_rawDesc), len(file_pkg_proto_user_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_user_v1_message_proto_goTypes,
		DependencyIndexes: file_pkg_proto_user_v1_message_proto_depIdxs,
		MessageInfos:      file_pkg_proto_user_v1_message_proto_msgTypes,
	}.Build()
	File_pkg_proto_user_v1_message_proto = out.File
	file_pkg_proto_user_v1_message_proto_goTypes = nil
	file_pkg_proto_user_v1_message_proto_depIdxs = nil
}
