// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/user/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pkg_proto_user_v1_service_proto protoreflect.FileDescriptor

const file_pkg_proto_user_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/user/v1/service.proto\x12\x13nortoo.usms.user.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fpkg/proto/user/v1/message.proto2\xbc\x06\n" +
	"\aService\x12C\n" +
	"\x06Create\x12\x1e.nortoo.usms.user.v1.CreateReq\x1a\x19.nortoo.usms.user.v1.User\x12@\n" +
	"\x06Delete\x12\x1e.nortoo.usms.user.v1.DeleteReq\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\x06Update\x12\x1e.nortoo.usms.user.v1.UpdateReq\x1a\x19.nortoo.usms.user.v1.User\x12=\n" +
	"\x03Get\x12\x1b.nortoo.usms.user.v1.GetReq\x1a\x19.nortoo.usms.user.v1.User\x12C\n" +
	"\x04List\x12\x1c.nortoo.usms.user.v1.ListReq\x1a\x1d.nortoo.usms.user.v1.ListResp\x12@\n" +
	"\x06Signup\x12\x1e.nortoo.usms.user.v1.SignupReq\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\x05Login\x12\x1d.nortoo.usms.user.v1.LoginReq\x1a\x1e.nortoo.usms.user.v1.LoginResp\x12C\n" +
	"\x04Auth\x12\x1c.nortoo.usms.user.v1.AuthReq\x1a\x1d.nortoo.usms.user.v1.AuthResp\x12P\n" +
	"\x0eChangePassword\x12&.nortoo.usms.user.v1.ChangePasswordReq\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\rResetPassword\x12%.nortoo.usms.user.v1.ResetPasswordReq\x1a\x16.google.protobuf.Empty\x12p\n" +
	"\x13DoesIdentifierExist\x12+.nortoo.usms.user.v1.DoesIdentifierExistReq\x1a,.nortoo.usms.user.v1.DoesIdentifierExistRespB-Z+github.com/nortoo/usms/pkg/proto/user/v1;v1b\x06proto3"

var file_pkg_proto_user_v1_service_proto_goTypes = []any{
	(*CreateReq)(nil),               // 0: nortoo.usms.user.v1.CreateReq
	(*DeleteReq)(nil),               // 1: nortoo.usms.user.v1.DeleteReq
	(*UpdateReq)(nil),               // 2: nortoo.usms.user.v1.UpdateReq
	(*GetReq)(nil),                  // 3: nortoo.usms.user.v1.GetReq
	(*ListReq)(nil),                 // 4: nortoo.usms.user.v1.ListReq
	(*SignupReq)(nil),               // 5: nortoo.usms.user.v1.SignupReq
	(*LoginReq)(nil),                // 6: nortoo.usms.user.v1.LoginReq
	(*AuthReq)(nil),                 // 7: nortoo.usms.user.v1.AuthReq
	(*ChangePasswordReq)(nil),       // 8: nortoo.usms.user.v1.ChangePasswordReq
	(*ResetPasswordReq)(nil),        // 9: nortoo.usms.user.v1.ResetPasswordReq
	(*DoesIdentifierExistReq)(nil),  // 10: nortoo.usms.user.v1.DoesIdentifierExistReq
	(*User)(nil),                    // 11: nortoo.usms.user.v1.User
	(*emptypb.Empty)(nil),           // 12: google.protobuf.Empty
	(*ListResp)(nil),                // 13: nortoo.usms.user.v1.ListResp
	(*LoginResp)(nil),               // 14: nortoo.usms.user.v1.LoginResp
	(*AuthResp)(nil),                // 15: nortoo.usms.user.v1.AuthResp
	(*DoesIdentifierExistResp)(nil), // 16: nortoo.usms.user.v1.DoesIdentifierExistResp
}
var file_pkg_proto_user_v1_service_proto_depIdxs = []int32{
	0,  // 0: nortoo.usms.user.v1.Service.Create:input_type -> nortoo.usms.user.v1.CreateReq
	1,  // 1: nortoo.usms.user.v1.Service.Delete:input_type -> nortoo.usms.user.v1.DeleteReq
	2,  // 2: nortoo.usms.user.v1.Service.Update:input_type -> nortoo.usms.user.v1.UpdateReq
	3,  // 3: nortoo.usms.user.v1.Service.Get:input_type -> nortoo.usms.user.v1.GetReq
	4,  // 4: nortoo.usms.user.v1.Service.List:input_type -> nortoo.usms.user.v1.ListReq
	5,  // 5: nortoo.usms.user.v1.Service.Signup:input_type -> nortoo.usms.user.v1.SignupReq
	6,  // 6: nortoo.usms.user.v1.Service.Login:input_type -> nortoo.usms.user.v1.LoginReq
	7,  // 7: nortoo.usms.user.v1.Service.Auth:input_type -> nortoo.usms.user.v1.AuthReq
	8,  // 8: nortoo.usms.user.v1.Service.ChangePassword:input_type -> nortoo.usms.user.v1.ChangePasswordReq
	9,  // 9: nortoo.usms.user.v1.Service.ResetPassword:input_type -> nortoo.usms.user.v1.ResetPasswordReq
	10, // 10: nortoo.usms.user.v1.Service.DoesIdentifierExist:input_type -> nortoo.usms.user.v1.DoesIdentifierExistReq
	11, // 11: nortoo.usms.user.v1.Service.Create:output_type -> nortoo.usms.user.v1.User
	12, // 12: nortoo.usms.user.v1.Service.Delete:output_type -> google.protobuf.Empty
	11, // 13: nortoo.usms.user.v1.Service.Update:output_type -> nortoo.usms.user.v1.User
	11, // 14: nortoo.usms.user.v1.Service.Get:output_type -> nortoo.usms.user.v1.User
	13, // 15: nortoo.usms.user.v1.Service.List:output_type -> nortoo.usms.user.v1.ListResp
	12, // 16: nortoo.usms.user.v1.Service.Signup:output_type -> google.protobuf.Empty
	14, // 17: nortoo.usms.user.v1.Service.Login:output_type -> nortoo.usms.user.v1.LoginResp
	15, // 18: nortoo.usms.user.v1.Service.Auth:output_type -> nortoo.usms.user.v1.AuthResp
	12, // 19: nortoo.usms.user.v1.Service.ChangePassword:output_type -> google.protobuf.Empty
	12, // 20: nortoo.usms.user.v1.Service.ResetPassword:output_type -> google.protobuf.Empty
	16, // 21: nortoo.usms.user.v1.Service.DoesIdentifierExist:output_type -> nortoo.usms.user.v1.DoesIdentifierExistResp
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_user_v1_service_proto_init() }
func file_pkg_proto_user_v1_service_proto_init() {
	if File_pkg_proto_user_v1_service_proto != nil {
		return
	}
	file_pkg_proto_user_v1_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_user_v1_service_proto_rawDesc), len(file_pkg_proto_user_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_user_v1_service_proto_goTypes,
		DependencyIndexes: file_pkg_proto_user_v1_service_proto_depIdxs,
	}.Build()
	File_pkg_proto_user_v1_service_proto = out.File
	file_pkg_proto_user_v1_service_proto_goTypes = nil
	file_pkg_proto_user_v1_service_proto_depIdxs = nil
}
